cloudfoundry/docs-buildpacks

- custom.html.md.erb
- index.html.md.erb
Please see https://www.pivotaltracker.com/story/show/86947488
Should also help close out: https://www.pivotaltracker.com/n/projects/1140488/stories/87004002
> Packaging docs

- ruby/sample-ror.html.md.erb
This commit will resolve the problem stated in https://www.pivotaltracker.com/story/show/88965078
> Updating the guide to test the sample app #88965078

- php/gsg-php-usage.html.md.erb
-c support has now been added to the PHP buildpack
[#86043066]
> Remove docs about ADDITIONAL_PREPROCESS_COMANNDS

- binary/index.html.md.erb
- index.html.md.erb
> Add documentation about the binary buildpack

- php/gsg-php-composer.html.md.erb
Signed-off-by: Anthony Emengo <aemengo@pivotal.io>
> Updates for php doc [#99170278]

- go/index.html.md.erb
[#102509846]
Signed-off-by: JT Archie <jtarchie@gmail.com>
> specify go version for .godir package management

- go/index.html.md.erb
Signed-off-by: Jordan Collier <jordanicollier@gmail.com>
> Update default go version to 1.5.1 [#102368720]

- node/node-service-bindings.html.md
> Fix "ampq" typo, changing to "amqp"

- custom.html.md.erb
See discussion at http://cf-dev.70369.x6.nabble.com/cf-dev-Droplets-and-Stacks-tp946p1096.html and request by buildpacks team (Mike M) for this PR.
> Precising usage of detect STDOUT string and associated best practice.

- go/index.html.md.erb
Signed-off-by: Brandon Shroyer <bshroyer@pivotal.io>
> remove godir mention [#108010602]

- custom.html.md.erb
Add documentation to custom buildpacks start command
[#111391006]
Signed-off-by: Dan Lavine <dlavine@us.ibm.com>
> Add documentation to custom buildpacks start command

- proxy-usage.html.md.erb
- toc.html.md.erb
`cf set-env http_proxy http://proxy-site.com:3000`
[#116609747]
> Add documentation for explaining proxy usage during staging

- staticfile/index.html.md.erb
> Add Staticfile buildpack documentation for SSI, gzip_static, and gunzip

- java/spring-service-bindings.html.md.erb
Replace service type DataSource with RedisConnectionFactory.
> Fix Redis connection factory config example.

- go/index.html.md.erb
- node/index.html.md.erb
- php/index.html.md.erb
- python/index.html.md.erb
- ruby/index.html.md.erb
- staticfile/index.html.md.erb
[#118310375]
Signed-off-by: David Jahn <david.a.jahn@gmail.com>
> Added links to supported versions for all buildpacks.

- node/index.html.md.erb
[#118775597]
Signed-off-by: David Jahn <david.a.jahn@gmail.com>
> Add section on how to specify an npm version

- python/index.html.md.erb
miniconda is a dependency managemenent tool added in v1.5.6
[#119736173]
Signed-off-by: Gabriel Ramirez <gabriel.e.ramirez@gmail.com>
> New Feature, miniconda in python buildpack

- python/index.html.md.erb
Tracker Story: https://www.pivotaltracker.com/story/show/121217121
> Instruct how to specify a start command when using Python buildpack

- custom.html.md.erb
- detection.html.md.erb
- index.html.md.erb
@RochesterinNYC and I did a doc jam a few weeks ago and produced these updates. More to come in the future. Putting in a pull now as what here is significant.
> Changes to custom, detection and index

- go/index.html.md.erb
> Document Glide support in the go buildpack

- binary/index.html.md.erb
- go/index.html.md.erb
- java/grails-service-bindings.html.md.erb
- java/java-tips.html.md.erb
- java/spring-service-bindings.html.md.erb
- node/node-service-bindings.html.md.erb
- ruby/gsg-ruby.html.md.erb
- ruby/ruby-service-bindings.html.md.erb
- ruby/sample-ror.html.md.erb
Spaces, it is aligned to view code with any editor, including the web page view (such as in the GitHub code). When use tabs, the view on the page is chaos, and it is terrible to mix tabs and spaces.
> Replace the tab with spaces

- custom.html.md.erb
Adding documentation for the new `default_versions` feature. 
[#126420317]
> Document new `default_versions` functionality.

- java/java-tips.html.md.erb
- Remove unnecessary semi-colon to avoid confusion.
> Remove unnecessary semicolon

- python/index.html.md.erb
To stay in sync with the buildpack
> Upgrade to Python 3.5.2

- staticfile/index.html.md.erb
an interview candidate got confused on this part because their application did not have a manifest
> Staticbuildpack update

- ruby/ruby-tips.html.md.erb
Full width turn half-width character
> “ should be "

- staticfile/index.html.md.erb
- Closes cloudfoundry/staticfile-buildpack#80
[#128127631]
> Add Staticfile buildpack notes about FORCE-HTTPS

- php/index.html.md.erb
[#128896127]
Signed-off-by: James Wen <jrw2175@columbia.edu>
> Fix Phalcon sample app link for PHP Buildpack docs

- developing-buildpacks.html.md.erb
- releasing_a_new_buildpack_version.html.md.erb
> Create page for releasing new buildpack versions

- developing-buildpacks.html.md.erb
- updating-buildpack-related-gems.html.md.erb
- add link from developing-buildpacks
[#125637781]
> Move updating buildpack-related gems to CF docs

- dotnet-core/index.html.md.erb
- index.html.md.erb
Ansers @pspinrad's questions regarding #102
> Make instructions clearer

- php/gsg-php-config.html.md.erb
> Fix PHP Buildpack Development Documentation link

- dotnet-core/index.html.md.erb
Adapted from original README.
[#133216479]
Signed-off-by: Jacques Chester <jchester@pivotal.io>
> Add section on disabling NuGet staging cache

- staticfile/index.html.md.erb
This is a new feature added to the staticfile buildpack
[#128980925]
> Add documentation on HSTS feature

- python/index.html.md.erb
- Only cf v245 is affected by this bug. No later versions are affected.
> Update Procfile warning in Python buildpack doc

- php/gsg-php-config.html.md.erb
[#133860339]
Signed-off-by: Jacques Chester <jchester@pivotal.io>
> Document difference between ZEND and PHP extensions

- index.html.md.erb
There are probably others out there that I don't know about...just wanted to get a list going. Thanks!
> link to community buildpacks

- dotnet-core/index.html.md.erb
> Update docs for MSBuild support

- dotnet-core/index.html.md.erb
- ruby/ruby-tips.html.md.erb
- for the .NET Core and Ruby buildpacks
[#135530371]
> Document ability to include custom shared librares in app

- dotnet-core/index.html.md.erb
These steps are no longer correct; we shouldn't tell people to do them.
[#137532113]
> Remove incorrect steps from .NET Core sample app

- upgrading_dependency_versions.html.md.erb
Signed-off-by: Keaty <kgross@pivotal.io>
> Update `Build the Binaries` to reflect splitting orphan branches into own repo

- node/index.html.md.erb
> Document using yarn in a disconnected environment

- staticfile/index.html.md.erb
> Document location_include in the Staticfile buildpack

- node/node-tips.html.md.erb
Remove duplicate express dependency in example package.json
> Update Tips for Node.js Applications

- php/gsg-php-config.html.md.erb
> Document new configuration of PHP EXTENSIONS and custom ini directories

- node/index.html.md.erb
See: https://yarnpkg.com/blog/2016/11/24/offline-mirror/
> Add .yarnrc to app dir in disconnected env

- ruby/index.html.md.erb
- ruby/windows.html.md.erb
> Document ruby windows behavior

- node/index.html.md.erb
[#141688835]
Signed-off-by: Nikita Rathi <nrathi@pivotal.io>
> Document lack of NPM integrity checks

- understand-buildpacks.html.md.erb
This PR fixes up the "Understanding Buildpacks" section.
> Multiple Buildpack Fixes

- releasing_a_new_buildpack_version.html.md.erb
> Update release instructions for buildpacks

- staticfile/index.html.md.erb
cloudfoundry/staticfile-buildpack#111 :eyes:
> Add some documentation for richer HSTS support

- staticfile/index.html.md.erb
Reverts cloudfoundry/docs-buildpacks#153
> Revert "Add some documentation for richer HSTS support"

- python/index.html.md.erb
Fixing minor issues in the python buildpack documentation.
> Minor corrections in laguage.

- python/index.html.md.erb
Reverts cloudfoundry/docs-buildpacks#160
> Revert "Minor corrections in laguage."

- java/java-client.html.md.erb
Recreated sample application with working code to list orgs, as per GitHub examples. Updated links and dependency versions for clarity.
> Updated dependencies, sample application, links

- python/index.html.md.erb
https://github.com/cloudfoundry/python-buildpack/releases/tag/v1.5.19
> document Pipenv support in the Python buildpack

- python/index.html.md.erb
> Discuss non-binary vendored dependencies for python

- go/index.html.md.erb
[#153191265]
Signed-off-by: Victoria Henry <vhenry@pivotal.io>
> Improve GOPACKAGENAME example

- php/gsg-php-increased-output.html.md.erb
- php/index.html.md.erb
Signed-off-by: Jack Feeny <jfeeny@pivotal.io>
> Document catch_workers_output [#141880113]

- go/index.html.md.erb
Because the go buildpack supports dep now 🎉
> Document go buildpack dep support.

- python/index.html.md.erb
[#156402108]
Signed-off-by: Tyler Phelan <tphelan@pivotal.io>
> Add docs for python-buildpacks NLTK feature.

- java/configuring-service-connections/spring-service-bindings.html.md.erb
getServiceConnector was using DataSource.class instead of MondoDbFactory.class
> Fix MongoDB configuration

- node/index.html.md.erb
See https://yarnpkg.com/lang/en/docs/prune-offline-mirror/
> Should also use yarn prune setting

- node/index.html.md.erb
- Clarify how to select yarn
- Give more information about offline vendoring and usage
[#159302357, #159291499]
Signed-off-by: Andrew Meyer <ameyer@pivotal.io>
> Updated nodejs buildpack docs:

- python/index.html.md.erb
Add instructions for configuring Conda to use a custom repo & how to properly validate certs for a custom repo.
> Update Python buildpack Conda instructions

- java/java-tips.html.md.erb
> Fix typo of blick to block

- buildpack-ci-index.html.md.erb
Also see https://github.com/concourse/concourse/issues/2416
> adjust concourse ci link

- staticfile/index.html.md.erb
Signed-off-by: Max Knee <Max_Knee@comcast.com>
> Adding Status Code directive

- dotnet-core/index.html.md.erb
> This page is for .NET Core on Linux only

- binary/index.html.md.erb
Adding additional info on how to handle .NET Core, self-hosted .NET Framework, and discouraging .NET console apps.
> Adding .NET Core details

- go/index.html.md.erb
- Remove 1.6 and 1.7 sections
[#165997614]
Co-authored-by: Guillermo Kardolus <gkardolus@pivotal.io>
> Add go-mod documentation

- index.html.md.erb
- sidecar-buildpacks.html.md.erb
[#169708825]
Co-authored-by: Daniel Thornton <dthornton@pivotal.io>
> initial commit for sidecar documentation

- nginx/index.html.md.erb
- includes list of statically compiled modules already available in the
nginx binary
- clarifies that this section is only describing how to load dynamic
modules
[#169805233]
Co-authored-by: Ryan Moran <rmoran@pivotal.io>
> Clarifies nginx module loading process

- go/index.html.md.erb
- nodejs-cnb/index.html.md.erb
> Nodejs cnb

- nodejs-cnb/index.html.md.erb
Adds Layer Reuse strategy outline for NPM
[#170138082]
[#170735825]
Co-authored-by: Ryan Moran <rmoran@pivotal.io>
> Updates NPM installation information and some environment variable entries

- developing-buildpacks.html.md.erb
Updated the first paragraph with a few grammatical updates.
> Fix typos on buildpacks documentation

- nodejs-cnb/index.html.md.erb
> remove docs for NODE_PATH, as it is no longer used

- java/java-tips.html.md.erb
This document was pretty old. This update attempts to bring it into a more modern era. Updating some items that changed with the JBP 3.x to 4.x transition like with memory configuration.
Signed-off-by: Daniel Mikusa <dmikusa@vmware.com>
> Update Java Tips

- dotnet-core/index.html.md.erb
- hwc/index.html.md.erb
I'm not positive this fixes the markdown rendering rendering issues seen in #323, but it should help a bit
> .NET buildpack markdown formatting and Microsoft link updates
