cloudfoundry/docs-buildpacks

node/node-tips.html.md
A customer pointed out to me that our docs (open source and the downstream consumers) a bit out of date. I've taking a stab at updating them to the most current version of the build pack (1.3). I'm not sure the information is complete, but I did verify it's correct when run against a basic hello world application. Running this by the buildpacks PM or someone in the know would be much appreciated!
Thanks!
=> node.js tips updates

ruby/ruby-service-bindings.html.md
...or is it < 4.1? I'm not quite understanding where the code is in [the buildpack](https://github.com/cloudfoundry/ruby-buildpack) that determines whether to [write the `database.yml`](https://github.com/cloudfoundry/ruby-buildpack/blob/v1.5.0/lib/language_pack/ruby.rb#L629-L694) or not, but the file isn't overwritten for me using Rails 4.2.3 on `ruby_buildpack-cached-v1.4.1`. Seems to be the case on v1.5.0 as well:
https://github.com/cloudfoundry/ruby-buildpack/blob/v1.5.0/spec/rails41_spec.rb#L16
Thanks!
=> clarify that database.yml is only overridden for Rails < 4

java/gsg-ratpack.html.md.erb, ruby/gsg-ruby.html.md.erb
According to `cf marketplace -s rediscloud`, the only plans offered are:
```
100mb          Basic                paid
250mb          Mini                 paid
500mb          Small                paid
1gb            Standard             paid
2-5gb          Medium               paid
5gb            Large                paid
10gb           X-Large              paid
50gb           XX-Large             paid
30mb           Lifetime Free Tier   free
```
The documentation in the getting started guide for both Ruby and Java says
to use the 25mb plan. I imagine that at some point the storage limit was
bumped to 30mb.
A very big thank you to @bridgetkromhout for pointing out where these docs
live!
Fixes docs.
=> 25mb rediscloud plan is no longer offered

java/gsg-ratpack.html.md.erb, ruby/gsg-ruby.html.md.erb
Reverts cloudfoundry/docs-buildpacks#41due to unsigned CLA. 
Hi Andrew, Our legal policy prevents me from accepting this PR without a signed CLA. I can make the changes on your behalf, or if you could please accept the CLA, we can accept the PR. Once you sign the CLA you will be able to contribute future PRs without any delay.
Thanks
=> Revert "25mb rediscloud plan is no longer offered"

java/gsg-ratpack.html.md.erb, ruby/gsg-ruby.html.md.erb
Reverts cloudfoundry/docs-buildpacks#42
This reversion to the reversion effectively accepts PR #41, which now has a signed CLA.
=> Revert "Revert "25mb rediscloud plan is no longer offered""

binary/index.html.md.erb, go/index.html.md.erb, node/index.html.md.erb, php/index.html.md.erb, python/index.html.md.erb, ruby/index.html.md.erb, staticfile/index.html.md.erb
Move documentation about deploying applications from buildpacks README to cf docs
[#118094267]
Signed-off-by: John Shahid <jvshahid@gmail.com>
=> Adding documentation about deploying applications and standardizing format

php/gsg-php-sessions.html.md.erb, php/gsg-php-usage.html.md.erb, php/index.html.md.erb, toc.html.md.erb
Add a `session` subsection to the php docs. The new section explains how to use `memcached` or `redis` as a session storage with php
[#118608021]
Signed-off-by: John Shahid <jvshahid@gmail.com>
=> Migrated documentation on sessions and buildpack logs from

ruby/index.html.md.erb
Primarily documents the functionality added here: https://www.pivotaltracker.com/story/show/106117082
=> [Ruby Buildpack] Add documentation for Gemfile `ruby` directive version operator support

staticfile/index.html.md.erb
It seems the section title was copy-pasted from the previous section, so I gave it the title "Custom Nginx Configuration".
Also, I was confused because I'd assumed that my `nginx.conf` should be in the same place as the root of my project folder that contains my application manifest, rather than the root directory static files are served out of. So I added a bit of documentation to clarify this.
=> Update "custom nginx configuration" section.

go/index.html.md.erb
- Closes cloudfoundry/go-buildpack#41
[#121378133]
Signed-off-by: Gabriel Ramirez <gabriel.e.ramirez@gmail.com>
=> Add example manifest for go buildpack native vendoring

java/java-client.html.md.erb
Update docs following https://github.com/cloudfoundry/cf-java-client/commit/2d1d29c7aaa1d24b41b85cbc5d9aa0f9b91061bf . 
Note also that the old instructions (accessing the `-spring` project) fail; even though the binaries are still in the repo they assume version information for `io.projectreactor:reactor-netty` which presumably was defined in a dependency but is no longer.
I have tested the deps and they work nicely, but I have not tried the java code.
=> CF client project is now `-reactor` not `-spring`

ruby/ruby-tips.html.md.erb
And link to the RubyGems page for it.
=> Fix typo in rails_serve_static_assets gem name

php/index.html.md.erb
- This Wordpress sample app does not work anymore, so we're removing it from the docs.
[#128896127]
=> Remove non-functional wordpress example from PHP buildpack docs

dotnet-core/index.html.md.erb, dotnet/index.html.md.erb
I copied most of it from the buildpack's website. We'd need to update the links as soon as the buildpack is moved from the uncubator space into the official one.
=> Add docs for .NET buildpack

ruby/gsg-ror.html.md.erb, ruby/ruby-service-bindings.html.md.erb
- Remove vague section about Rails 4 and database config from ruby
buildpack services docs
[#128506411]
=> Add docs for Ruby buildpack Rails database configuration

ruby/ruby-tips.html.md.erb
- This section is not very informative and the default Ruby version is
way out of date.
[#130455827]
=> Remove 'Additional Ruby Buildpack Information'

node/index.html.md.erb
- Make it clear that vendoring app dependencies is not exclusively for
disconnected environments
[#116369631]
=> Rewrite node vendoring section for clarity

python/index.html.md.erb
Added a section to the Python page to match the [Ruby](https://docs.cloudfoundry.org/buildpacks/ruby/ruby-service-bindings.html#cf-app-utils) and [Node.js](https://docs.cloudfoundry.org/buildpacks/node/node-service-bindings.html#cfenv) pages.
/cc @jmcarp
=> link to py-cfenv package

python/index.html.md.erb
Workaround to [this bug](https://www.pivotaltracker.com/n/projects/966314/stories/132190561). Would be great to be able to revert this soon, but I personally think it's worth putting it in for now, as people on my team get bitten by it regularly.
/cc @jberkhahn @utako
=> require Procfile for Python apps in CF >= 245

python/index.html.md.erb
As I understand it, vendoring is only required when disconnected from the Internet.
The previous wording implied that it was mandatory for all users. 
Ideally we wouldn't ask users to do anything they don't need to do. One of my colleagues, who is new to Cloud Foundry, got sent down a bit of a rabbithole trying to get the vendoring steps to work when he didn't need to.
=> Make it clear that vendoring is optional

ruby/ruby-environment.html.md.erb, ruby/ruby-service-bindings.html.md.erb, ruby/ruby-tips.html.md.erb
- Cloud Foundry creates the environment variable, not the buildpack
[#136783989]
=> Fix DATABASE_URL docs

binary/index.html.md.erb, go/index.html.md.erb, php/index.html.md.erb, python/index.html.md.erb, ruby/index.html.md.erb
The current documentation says that the buildpack will automatically
include the certificates configured in bosh using [1] in the
director.trusted_certs property of the bosh director.
But this does not appear to be the case. We were not able to find any
logic related to implement such behaviour, and it does violate the
principle of the container, where the staging or runtime will not be
able to access the Host VM filesystem. We tested it and it does not seem
to work.
Instead, CF provides two strategies to inject custom certs into the
application container, as described in [2], by setting the CF manifest
properties by either setting cflinuxfs2-rootfs.trusted_certs or
diego.rep.trusted_certs.
This second approach does work[3][4] and makes sense to be the
recommeded way.
In this PR we update …
=> Update docs to add custom trusted certs

java/getting-started-deploying-apps/gsg-spring.html.md.erb
The CF jenkins plugin chokes on them because the jar is malformed
=> discourage spring "fully executable jars"

staticfile/index.html.md.erb
When reading the config option descriptions table, it's easy to feel a bit confused and wonder how to actually apply the options, so this is a small tip to look at the table below. It could be even better for these two tables to be integrated together in some fashion ([dropped a note in #cf-docs to suggest this](https://cloudfoundry.slack.com/archives/C03B0T0D5/p1504914459000085)) - this is just a small suggestion to help readers without requiring a big refactor.
=> On Staticfile page, small edit to help people find config implementation details

custom.html.md.erb
Investigated with @sclevine: it's not implemented. "Repo" attribute of URL (the part after `#`) is passed to `git clone git-url -b repo` and `git` only accepts branch names and tags, not commit shas
=> removed reference on setting buildpack with commit sha - not supported

use-multiple-buildpacks.html.md.erb
Looks like .cfignore has been honored since https://github.com/cloudfoundry/cli/commit/46f01211f40f89fae726af989e0adbd64e165eac
=> Delete .cfignore and v3-push warning

node/node-tips.html.md.erb
`id='port'` is already used by the previous section
=> Fix link to the memory section

binary/index.html.md.erb
I was trying the link as is from the documentation i.e. 
`cf push test-app -b https://github.com/cloudfoundry/binary_buildpack.git`  and got errors
```
Downloading app package...
Downloaded app package (2.3M)
Failed to clone git repository at https://github.com/cloudfoundry/binary_buildpack.git
Exit status 1
``` 
I realize the `_` should be a `-` so the link is `cf push my_app -b https://github.com/cloudfoundry/binary-buildpack.git`
=> Documentation has incorrect link for the binary buildpack

node/node-tips.html.md.erb
The Node Buildpack Tips for Applications section about Low Memory Environments is only supported by node versions 6.12.0 and greater. Versions >6.12.0, 8.x, and 9.x will all support OPTIMIZE_MEMORY.
=> Update node docs with OPTIMIZE_MEMORY version requirement

index.html.md.erb, nginx/index.html.md.erb
Added new documentation for the NGINX buildpack.  This covers how to setup your NGINX app structure to work with the buildpack and then also push the app using the NGINX buildpack.
Also added links to the main buildpack page for NGINX.
=> Added documentation for new NGINX builpack

staticfile/index.html.md.erb
Using a custom `nginx.conf` in Staticfile buildpack is deprecated as per: https://github.com/cloudfoundry/staticfile-buildpack/commit/9c9ae2c1f27a450bf73c87b02261f2813f45d9db
This PR changes the documentation to reflect that and point users to the NGINX buildpack if they require this functionality.
=> point to nginx buildpack for custom configuration

dotnet-core/index.html.md.erb
- dotnet-core project.json documentation is removed because it is deprecated
Signed-off-by: Tyler Phelan <tphelan@pivotal.io>
=> Update dotnet-core docs with .runtimeconfig.json .NET framework versioning

staticfile/index.html.md.erb
Previously it was incorrectly stated:
> Set the location_include variable in your Staticfile to the path of the file from the previous step:
As the path from the previous step was `nginx/conf/includes/custom_header.conf` and the path in `Staticfile` is `includes/*.conf` 
This PR reflects that the required path is relative to `nginx/conf`
=> reflect required path in Staticfile

dotnet-core/index.html.md.erb
- Add SDK selection info
- Buildpack.yml can be used to specify .NET SDK version and version line
- Remove deprecated project.json
- Add precedence list for .NET SDK versioning
[#157975969]
Signed-off-by: Andrew Meyer <ameyer@pivotal.io>
=> Update dotnet-core docs

nginx/index.html.md.erb
This shouldn't be merged until we're ready to release NGINX 1.0.0, because it documents only the new syntax.
There is new templating syntax that supersedes the old one:
- `{{port}}`
- `{{env "variable_name"}}`
- `{{module "builtin_module_name"}}`
The default nginx setup has changed a little (nginx.yml -> buildpacks.yml)
Also, we put the standard "how to push with this buildpack" section at the top
[#155953917, #156618438]
Signed-off-by: Danny Joyce <djoyce@pivotal.io>
=> Updates for NGINX buildpack 1.0.0 features.

dotnet-core/index.html.md.erb
[Fixes issue #202]
New snippet uses <PropertyGroup> instead of package reference.
=> Fix .csproj example for locking .NET framework version

python/index.html.md.erb
This new section talks about how to setup a flag for `pip` to point to an internal dependency repository and incorporates the certificate workaround defined [here](https://github.com/cloudfoundry/python-buildpack/issues/100)
I think surfacing this information in docs is preferable to having it buried in an issue on the buildpack. It also fills the gap between online and offline use.
=> Adding section for private repos

nginx/index.html.md.erb
RE: #219; The documention currently references the incorrect filename for `buildpack.yml`, this PR corrects the filename from `buildpacks.yml` -> `buildpack.yml`.
As seen, I think linking to an example format for this file would be helpful.
The correct filename reference can be seen here: https://github.com/cloudfoundry/nginx-buildpack/blob/3d84c52ecd32da531ddaa1a1cc61b5d247f3277c/src/nginx/supply/supply.go#L118
=> Correct documented buildpacks.yml filename

go/index.html.md.erb
For the "Pass a Symbol and String to the Linker" section, we fixed a broken link and provided a new link to a sample app.
=> Fix broken link

stack-association.html.md.erb
This page had incorrect instructions for using cf update-buildpack to associate an already-uploaded buildpack: https://docs.cloudfoundry.org/buildpacks/stack-association.html
Fixed the mistake. Also see: #161850619
=> Update the instructions for using cf update-buildpack

go/index.html.md.erb
While playing around with the go buildpack I found this wrong link and fixed it.
=> Fixed wrong link to go sample app

java/configuring-service-connections/spring-service-bindings.html.md.erb
This PR fixes the issue reported in #222 and simplifies similar sections in the documentation. 
The information here summarizes the information available in the [Spring Cloud Connectors documentation](https://cloud.spring.io/spring-cloud-connectors/spring-cloud-connectors.html), showing a small subset of the configuration options that are possible with Connectors. A page within the Connectors documentation is linked under [`Auto-Reconfiguration`](https://docs.cloudfoundry.org/buildpacks/java/configuring-service-connections/spring-service-bindings.html#auto), but it might be good to add more explicit links to the Connectors documentation along with the Java configuration examples. 
Fixes #222
=> Fix usage of Spring Cloud Connectors for Spring Java config.

java/getting-started-deploying-apps/gsg-spring.html.md.erb
jars are more common and showing the example with "war" might make newer folks wonder if a war is preferred.
=> Suggest having sample push show a jar file rather than war.

r/index.html.md.erb
The buildpack [looks for a `num_threads` option in the `r.yml` file](https://github.com/cloudfoundry/r-buildpack/blob/c00ad2964784206f901723ca6cac052f1915c333/src/r/supply/supply.go#L52) and [supplies it as the `Ncpus` parameter to the invocation of `install.packages()`](https://github.com/cloudfoundry/r-buildpack/blob/c00ad2964784206f901723ca6cac052f1915c333/src/r/supply/supply.go#L119). That was [implemented here](https://github.com/cloudfoundry/r-buildpack/pull/3) but not documented.
This behavior is _extremely useful_ because it speeds up staging for R apps, potentially avoiding the default 15-minute staging timeout. When this flag was configured to match the number of CPUs available on our hosts, one cloud.gov customer reported a 38% speedup of staging time.
=> Document the "num_threads" parallel install option

python/index.html.md.erb
I had to dig for a working example to find out which port this buildpack expects me to expose.  The `host='0.0.0.0'` is  also tricky enough to include in the docs, IMHO.
=> Include information on the port

node/index.html.md.erb, staticfile/index.html.md.erb
- adds overview header to Node.js docs
=> Removes BOSH trusted cert warning from Staticfile docs

go/index.html.md.erb
[#166781190](https://www.pivotaltracker.com/story/show/166781190)
We were pushing a Go app and spent a bit of time trying to figure this out.
We are not sure if this should be under the Go Modules section or some other
part of the page. We tested with Go Modules so we are putting it under that 
header. I am not sure of other packaging systems have their own way of 
specifying subdirectory main packages.
cc: @matt-royal
=> document `package main` in a subdirectory

java/java-tips.html.md.erb
Tips for Java Developers page has 7 broken links resulting in 404.
This is because it was pointing to the [**master** branch that no longer exists](https://github.com/cloudfoundry/java-buildpack/issues/814).
Updated all links to use the new default branch **main**.
=> Fixed broken links on the Tips for Java Developers page

binary/index.html.md.erb
The current steps for pushing a .NET core app onto the v2 Windows Stack, using the `binary-buildpack` causes a failure. This change updates the `binary buildpack` documentation to remove the deprecated flag `--server.urls` from the custom start command for .NET core apps.
=> Remove deprecated flag from custom start command

README.md, custom.html.md.erb, index.html.md.erb
This is not currently supported, and so should not be documented.
/cc @kvedurmu
=> Removes references to CF-compatible CNBs

staticfile/index.html.md.erb
This PR clarifies that root content is distinct from location of the nginx directives directory.
=> Clarify alternative root content in static buildpack

sidecar-buildpacks.html.md.erb
These were intended to be GA last July, but the docs were not updated.
cc @dsboulder @anEXPer @elenasharma
=> Remove beta tag from sidecar buildpacks

java/index.html.md.erb, java/java-native-image.html.md.erb
Adds a section for users wanting to build and deploy Java native image applications on Cloud Foundry.
=> Add instructions for deploying Java Native Image apps

staticfile/index.html.md.erb
- Implementation PR: https://github.com/cloudfoundry/staticfile-buildpack/pull/254
[cloudfoundry/routing-release#200]
cc @robdimsdale
=> Add HTTP/2 configuration to Staticfile docs

nginx/index.html.md.erb
[This feature](https://github.com/cloudfoundry/nginx-buildpack/pull/12) was not documented previously. It should be, since putting the app that an nginx proxy points to on an internal route is good practice! So here are some docs.
=> Document how to resolve internal routes

stack-association.html.md.erb
* remove outdated information on cflinuxfs2, capi-release 1.58.0 (2018) and CF CLI v6
* add information on cflinuxfs4 / Ubuntu Jammy
* remove "rename-buildpack" command docu (is now "update-buildpack --rename")
=> Update stack-related documentation

python/index.html.md.erb
As per the [documentation of pip](https://pip.pypa.io/en/stable/cli/pip_install/#cmdoption-no-binary)
> Do not use binary packages. [..] Accepts either “:all:” to disable all binary packages, “:none:” to empty the set (notice the colons)
i.e. the command, as it stood, installed binary packages (wheels) only and the explanation was wrong: in the buildpack you're likely to not have all relevant header files that you need for compiling the packages; better to vendor wheels instead.
=> Fix pip vendor command explanation

java/index.html.md.erb
Java Buildpack v3 is long out of support, removing outdated references to it from the memory constraints section
=> Update memory constraints in index.html.md.erb

dotnet-core/index.html.md.erb
Document issue in .NET Core buildpack and workaround
=> .NET Core: document NTLM auth known issue and workaround

cnb/index.html.md.erb
This change documents how to pull Cloud Native Buildpacks from private registries using CLI v8.9.0 (or later).
=> Document pulling CNBs from private registires

cnb/index.html.md.erb
We are working on System CNBs in this PR: https://github.com/cloudfoundry/cloud_controller_ng/pull/4342
To be merged + released later this week.
=> Add documentation for System CNBs

cnb/index.html.md.erb
Support for GCR has been discontinued and buildpacks should now be pulled from Docker Hub.
See: https://blog.paketo.io/posts/paketo-gcr-registry-sunset/
=> fix: adjust CNB URL to Docker Hub
